from __future__ import annotations

import json
from typing import Any

import httpx

from .config import settings
from .models import CodePlan, CodeFileProposal


class DeepSeekClient:
    def __init__(self) -> None:
        self._api_key = settings.deepseek_api_key
        self._base_url = settings.deepseek_base_url.rstrip("/")
        self._model = settings.deepseek_model

    def _fallback_code_plan(self, task: str) -> CodePlan:
        content = (
            "# Auto-generated draft\n\n"
            f"Task: {task}\n\n"
            "This file was generated by fallback logic because DeepSeek API key is missing."
        )
        return CodePlan(
            summary="Fallback plan generated without DeepSeek API.",
            files=[CodeFileProposal(path="AUTO_GENERATED_TASK.md", content=content)],
            local_commands=[],
        )

    async def _chat(self, system_prompt: str, user_prompt: str) -> str:
        if not self._api_key:
            return ""

        payload = {
            "model": self._model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.1,
            "response_format": {"type": "json_object"},
        }
        headers = {"Authorization": f"Bearer {self._api_key}", "Content-Type": "application/json"}
        async with httpx.AsyncClient(timeout=120) as client:
            response = await client.post(f"{self._base_url}/chat/completions", json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"]

    async def build_code_plan(self, task_text: str, context_md: str) -> CodePlan:
        if not self._api_key:
            return self._fallback_code_plan(task_text)

        system_prompt = (
            "You are a senior software architect and Python engineer. "
            "Return strict JSON with keys: summary, files, local_commands. "
            "files is array of objects: {path, content}. "
            "Only produce relevant project files."
        )
        user_prompt = (
            f"Business task:\n{task_text}\n\n"
            f"Context docs:\n{context_md}\n\n"
            "Generate implementation draft for a Python/FastAPI project."
        )
        raw = await self._chat(system_prompt, user_prompt)
        try:
            parsed: dict[str, Any] = json.loads(raw)
            return CodePlan(**parsed)
        except Exception:
            return self._fallback_code_plan(task_text)

    async def review_and_fix_hint(self, task_text: str, last_error: str, context_md: str) -> str:
        if not self._api_key:
            return "Fallback review: inspect deployment logs and ensure docker compose services are healthy."
        system_prompt = "You are a strict code reviewer. Return JSON with key: fix_hint."
        user_prompt = (
            f"Task:\n{task_text}\n\nLast deployment or test error:\n{last_error}\n\nContext:\n{context_md}"
        )
        raw = await self._chat(system_prompt, user_prompt)
        try:
            parsed = json.loads(raw)
            return str(parsed.get("fix_hint", "No fix hint provided."))
        except Exception:
            return "Failed to parse review response. Check logs and deployment steps."
