from __future__ import annotations

import ast
import json
import re
from typing import Any

import httpx

from .config import settings
from .models import CodeFileProposal, CodePlan, RepairPlan


class DeepSeekClient:
    def __init__(self) -> None:
        self._api_key = settings.deepseek_api_key
        self._base_url = settings.deepseek_base_url.rstrip("/")
        self._model = settings.deepseek_model

    def _fallback_code_plan(self, task: str) -> CodePlan:
        content = (
            "# Auto-generated draft\n\n"
            f"Task: {task}\n\n"
            "This file was generated by fallback logic because DeepSeek API key is missing."
        )
        return CodePlan(
            summary="Fallback plan generated without DeepSeek API.",
            files=[CodeFileProposal(path="AUTO_GENERATED_TASK.md", content=content)],
            local_commands=[],
        )

    async def _chat(self, system_prompt: str, user_prompt: str) -> str:
        if not self._api_key:
            return ""

        payload = {
            "model": self._model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.1,
            "response_format": {"type": "json_object"},
        }
        headers = {"Authorization": f"Bearer {self._api_key}", "Content-Type": "application/json"}
        async with httpx.AsyncClient(timeout=120) as client:
            response = await client.post(f"{self._base_url}/chat/completions", json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"]

    def _parse_json_relaxed(self, raw: str) -> dict[str, Any] | None:
        if not raw:
            return None
        cleaned = raw.strip()
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)
        try:
            return json.loads(cleaned)
        except Exception:
            pass
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start != -1 and end != -1 and end > start:
            snippet = cleaned[start : end + 1]
            try:
                return json.loads(snippet)
            except Exception:
                try:
                    # Some model outputs contain single quotes or python-like dicts.
                    parsed_any = ast.literal_eval(snippet)
                    if isinstance(parsed_any, dict):
                        return parsed_any
                except Exception:
                    return None
        return None

    def _validate_repair_plan_payload(self, parsed: dict[str, Any]) -> tuple[bool, str]:
        actions = parsed.get("actions")
        if not isinstance(actions, list) or not actions:
            return False, "actions must be a non-empty array"

        allowed = {
            "run_remote_command",
            "run_local_command",
            "replace_text_in_file",
            "update_healthcheck_url",
            "ensure_postgres_db",
        }
        for idx, action in enumerate(actions):
            if not isinstance(action, dict):
                return False, f"actions[{idx}] must be an object"
            action_type = str(action.get("action_type", "")).strip().lower()
            if action_type not in allowed:
                return False, f"actions[{idx}].action_type is invalid"
            if action_type in {"run_remote_command", "run_local_command"} and not str(action.get("command", "")).strip():
                return False, f"actions[{idx}].command is required for {action_type}"
            if action_type == "run_local_command":
                cmd = str(action.get("command", "")).strip().lower()
                # In this orchestrator, repair loop targets deployed environment.
                # Local commands frequently create loops and should not be used.
                return False, f"actions[{idx}].run_local_command is not allowed in repair plans (use run_remote_command): {cmd}"
            if action_type == "replace_text_in_file":
                if not str(action.get("file_path", "")).strip():
                    return False, f"actions[{idx}].file_path is required for replace_text_in_file"
                if not str(action.get("find_text", "")).strip():
                    return False, f"actions[{idx}].find_text is required for replace_text_in_file"
                if "replace_text" not in action or action.get("replace_text") is None:
                    return False, f"actions[{idx}].replace_text is required for replace_text_in_file (string, use \"\" to delete find_text)"
                if str(action.get("find_text", "")).strip() == str(action.get("replace_text", "")).strip():
                    return False, f"actions[{idx}].find_text and replace_text must differ for replace_text_in_file"

        return True, ""

    async def build_code_plan(self, task_text: str, context_md: str) -> CodePlan:
        if not self._api_key:
            return self._fallback_code_plan(task_text)

        system_prompt = (
            "You are a senior software architect and Python engineer. "
            "Return strict JSON with keys: summary, files, local_commands. "
            "files is array of objects: {path, content}. "
            "Only produce relevant project files."
        )
        user_prompt = (
            f"Business task:\n{task_text}\n\n"
            f"Context docs:\n{context_md}\n\n"
            "Generate implementation draft for a Python/FastAPI project."
        )
        raw = await self._chat(system_prompt, user_prompt)
        try:
            parsed: dict[str, Any] = json.loads(raw)
            return CodePlan(**parsed)
        except Exception:
            return self._fallback_code_plan(task_text)

    async def generate_file_content(
        self,
        task_text: str,
        context_md: str,
        file_path: str,
        generated_files_md: str,
        base_file_content: str,
        dependency_context_md: str = "",
        invariants_md: str = "",
    ) -> str:
        if not self._api_key:
            if base_file_content:
                return base_file_content
            return f"# Fallback content for {file_path}\n"

        system_prompt = (
            "You are a senior Python full-stack engineer. "
            "Return strict JSON with key: content. "
            "Generate code for a single file with path provided by user. "
            "Respect already generated files and keep API/import consistency."
        )
        user_prompt = (
            f"Business task:\n{task_text}\n\n"
            f"Context docs:\n{context_md}\n\n"
            f"Hard invariants (must not be violated):\n{invariants_md}\n\n"
            f"Target file path:\n{file_path}\n\n"
            f"Current file content from repository (if exists):\n{base_file_content}\n\n"
            f"Dependency-aware retrieved context:\n{dependency_context_md}\n\n"
            f"Already generated key files:\n{generated_files_md}\n\n"
            "Generate final content for the target file. Keep consistency with dependencies and invariants."
        )
        raw = await self._chat(system_prompt, user_prompt)
        try:
            parsed: dict[str, Any] = json.loads(raw)
            content = str(parsed.get("content", "")).strip()
            if content:
                return content + ("\n" if not content.endswith("\n") else "")
        except Exception:
            pass
        return base_file_content or f"# Empty content generated for {file_path}\n"

    async def build_architecture_spec(self, task_text: str, context_md: str, architect_prompt: str | None = None) -> str:
        if not self._api_key:
            return (
                "# Project context\n\n"
                "## Goal\n"
                f"{task_text}\n\n"
                "## Tech stack\n"
                "- Python 3.11\n- FastAPI\n- Docker\n\n"
                "## Functional requirements\n- Define core endpoints and expected behavior.\n\n"
                "## Non-functional requirements\n- Basic reliability and readability.\n\n"
                "## Project structure requirements\n- main application entrypoint and dependency file.\n\n"
                "## Run requirements\n- Containerized startup command.\n\n"
                "## Acceptance criteria\n- Main endpoint responds successfully."
            )

        system_prompt = architect_prompt.strip() if architect_prompt else settings.architect_system_prompt
        user_prompt = (
            f"Business task:\n{task_text}\n\n"
            f"Context docs:\n{context_md}\n\n"
            "Generate architecture specification markdown for implementation."
        )
        raw = await self._chat(system_prompt, user_prompt)
        try:
            parsed: dict[str, Any] = json.loads(raw)
            spec = str(parsed.get("architecture_spec_markdown", "")).strip()
            if spec:
                return spec
        except Exception:
            pass
        return (
            "# Project context\n\n"
            "## Goal\n"
            f"{task_text}\n\n"
            "## Tech stack\n"
            "- Python 3.11\n- FastAPI\n- Docker\n\n"
            "## Functional requirements\n- Define required API and behavior.\n\n"
            "## Non-functional requirements\n- Stability and maintainability.\n\n"
            "## Project structure requirements\n- Clear project layout and dependencies.\n\n"
            "## Run requirements\n- Provide container startup flow.\n\n"
            "## Acceptance criteria\n- Health endpoint returns success."
        )

    async def review_and_fix_hint(self, task_text: str, last_error: str, context_md: str) -> str:
        if not self._api_key:
            return "Fallback review: inspect deployment logs and ensure docker compose services are healthy."
        system_prompt = "You are a strict code reviewer. Return JSON with key: fix_hint."
        user_prompt = (
            f"Task:\n{task_text}\n\nLast deployment or test error:\n{last_error}\n\nContext:\n{context_md}"
        )
        raw = await self._chat(system_prompt, user_prompt)
        try:
            parsed = json.loads(raw)
            return str(parsed.get("fix_hint", "No fix hint provided."))
        except Exception:
            return "Failed to parse review response. Check logs and deployment steps."

    async def propose_repair_plan(
        self,
        task_text: str,
        last_error: str,
        context_md: str,
        runtime_facts: str,
    ) -> RepairPlan:
        if not self._api_key:
            return RepairPlan(
                diagnosis="Fallback repair plan without model.",
                confidence=0.2,
                actions=[],
                expected_outcome="No actions generated in fallback mode.",
                validation_steps=[],
            )

        system_prompt = (
            "You are the sole repair agent: you take full responsibility for fixing the project so the pipeline succeeds. "
            "No other layer will silently patch files for you. "
            "Work in two phases: diagnose from the Error line and Runtime facts, then apply treatment. "
            "Return strict JSON only (no markdown). "
            "Required top-level keys: diagnosis(string), confidence(number 0..1), actions(array), expected_outcome(string), validation_steps(array of strings). "
            "Each action must include: action_type, target, command, file_path, find_text, replace_text, reason. "
            "Allowed action_type values: run_remote_command, run_local_command, replace_text_in_file, update_healthcheck_url, ensure_postgres_db. "
            "Use run_remote_command for diagnostics and runtime/deployment actions. "
            "Do NOT use run_local_command in repair plans. "
            "When editing files, file_path must be relative to repository root (e.g., docker-compose.yml), not absolute remote paths. "
            "replace_text_in_file: find_text MUST be copied verbatim from the repository excerpt in runtime facts (same quotes, spaces, newlines). "
            "Never invent port mappings (e.g. guessing 8085:8085); only use text that actually appears in the excerpt. "
            "Docker Compose rule: each host port (left side of host:container in ports:) must appear at most once in the file. "
            "If the error says a host port is mapped more than once, you MUST edit docker-compose (or compose.yml) so only one service publishes that host port "
            "(e.g. remove the duplicate ports: entry from nginx/frontend or change its published host port). "
            "Use 'docker compose' syntax (not docker-compose) when suggesting shell commands. "
            "Execution order (orchestrator): every replace_text_in_file runs first; then git commit/push and server git pull + docker compose up (when auto_deploy); then run_remote_command actions in plan order; then validation_steps. "
            "So remote shell commands always see the repository after your file edits—do not assume the server is stale relative to find_text. "
            "The section recent_repair_feedback lists failures from the current incident only (since the last successful repair). "
            "Do not repeat the same failed find_text or shell command unless you state what changed in the repo or on the host. "
            "If diagnosis is uncertain, first actions may be diagnostic run_remote_command steps that gather decisive facts. "
            "For run_remote_command/run_local_command, command MUST be non-empty and executable as-is. "
            "For replace_text_in_file, replace_text is the replacement substring (use empty string only when intentionally removing find_text). "
            "Include explicit validation_steps as executable commands (quoted). "
            "Do not return empty actions unless no safe action exists."
        )
        user_prompt = (
            f"Business task:\n{task_text}\n\n"
            f"Error (primary signal):\n{last_error}\n\n"
            f"Runtime facts (includes compose excerpt and recent_repair_feedback when present):\n{runtime_facts}\n\n"
            f"Context docs:\n{context_md}\n\n"
            "Produce a repair plan whose actions you can defend: file edits must match the excerpt exactly; remote commands must be safe and minimal."
        )
        validation_feedback = ""
        for _ in range(3):
            prompt = user_prompt
            if validation_feedback:
                prompt += (
                    "\n\nPrevious response was rejected. Fix it and return JSON again.\n"
                    f"Validation error: {validation_feedback}\n"
                    "Return ONLY JSON object."
                )
            raw = await self._chat(system_prompt, prompt)
            parsed = self._parse_json_relaxed(raw)
            if parsed is None:
                validation_feedback = "invalid JSON format"
                continue
            valid, reason = self._validate_repair_plan_payload(parsed)
            if not valid:
                validation_feedback = reason
                continue
            try:
                return RepairPlan(**parsed)
            except Exception as exc:
                validation_feedback = f"schema validation failed: {exc}"
                continue
        return RepairPlan(
            diagnosis=f"Failed to build valid repair plan JSON. {validation_feedback or 'Unknown parsing issue.'}",
            confidence=0.1,
            actions=[],
            expected_outcome="No executable repair actions.",
            validation_steps=[],
        )
